apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: queuecraft-prod
resources:
  - ../../base
  - namespace.yml
patches:
  - path: ingress.yml
images:
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-api
    newTag: prod
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-web
    newTag: prod
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-migration
    newTag: prod