apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: queuecraft
resources:
  - ../../base
  - api-env.yml
  - pg-deployment.yml
  - pg-env.yml
  - pvc.yml
images:
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-api
    newTag: 'prod'
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-web
    newTag: 'prod'
  - name: srvnexusint.hopital.chdn.lan:6443/infra/queuecraft-builder
    newTag: 'prod'