apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-env
  namespace: queuecraft
spec:
  encryptedData:
    POSTGRES_DB: REPLACE_WITH_KUBESEAL_OUTPUT
    POSTGRES_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
    POSTGRES_USER: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: pg-env
      namespace: queuecraft