apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-queuecraft-pg-data-pvc
  namespace: queuecraft
  labels:
    team: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi