import { randomUUID } from "node:crypto";
import nodemailer from "nodemailer";
import { db, notificationOutboxTable } from "@workspace/db";
import { and, eq, inArray, lte, ne, sql } from "drizzle-orm";
import { config } from "../config";
import { getRuntimeSettings } from "./application-settings";
import { logger } from "../lib/logger";
import { BREAK_GLASS_NOTIFICATION_ACTION } from "./notifications";

async function getTransporter() {
  const settings = await getRuntimeSettings();
  const smtp = { host: settings.smtpHost ?? config.smtp.host, port: settings.smtpPort ?? config.smtp.port, secure: settings.smtpSecure ?? config.smtp.secure, user: settings.smtpUser ?? config.smtp.user, password: settings.smtpPassword ?? config.smtp.password, from: settings.smtpFrom ?? config.smtp.from, fromName: settings.smtpFromName };
  if (!smtp.host) return { transporter: null, smtp };
  return { transporter: nodemailer.createTransport({
      host: smtp.host, port: smtp.port, secure: smtp.secure,
      auth:
        smtp.user && smtp.password
          ? { user: smtp.user, pass: smtp.password }
          : undefined,
      tls: { rejectUnauthorized: false },
    }), smtp };
}

export async function sendTestMail(recipient: string) {
  const { transporter, smtp } = await getTransporter();
  if (!transporter) throw new Error("SMTP is not configured");
  await transporter.sendMail({
    from: smtp.fromName ? { name: smtp.fromName, address: smtp.from } : smtp.from,
    to: recipient,
    subject: "QueueCraft test email",
    text: "This is a QueueCraft SMTP test email. Your mail settings are working.",
  });
}

export async function queueMail(executor: any, input: {
  topicId?: string;
  recipient: string;
  subject: string;
  body: string;
}) {
  const id = randomUUID();
  await executor.insert(notificationOutboxTable).values({
    id,
    topicId: input.topicId,
    recipient: input.recipient,
    action: BREAK_GLASS_NOTIFICATION_ACTION,
    subject: input.subject,
    body: input.body,
    nextAttemptAt: new Date(),
  });
  return id;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character]!);
}

function renderUrgentNotificationHtml(subject: string, body: string) {
  return `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#17324d">
    <div style="max-width:680px;margin:24px auto;background:#fff;border:1px solid #dce5ef;border-radius:8px;overflow:hidden">
      <div style="background:#ff7000;padding:22px 26px;color:#fff"><div style="font-size:12px;letter-spacing:2px;text-transform:uppercase">QueueCraft</div><h1 style="margin:8px 0 0;font-size:22px">${escapeHtml(subject)}</h1></div>
      <div style="padding:22px 26px;font-size:14px;line-height:1.6;white-space:pre-wrap">${escapeHtml(body)}</div>
      <div style="padding:14px 26px;background:#f8fafc;color:#64748b;font-size:12px">This security notification was generated by QueueCraft.</div>
    </div></body></html>`;
}

export function renderNotificationDigest(items: Array<typeof notificationOutboxTable.$inferSelect>) {
  const rows = items.map((item) => `
    <tr>
      <td style="padding:12px 14px;border-bottom:1px solid #dce5ef;color:#17324d">${escapeHtml(item.topicTitle || "Topic")}</td>
      <td style="padding:12px 14px;border-bottom:1px solid #dce5ef;font-weight:600;color:#17324d">${escapeHtml(item.action)}</td>
      <td style="padding:12px 14px;border-bottom:1px solid #dce5ef;color:#334155;white-space:pre-wrap">${escapeHtml(item.body)}</td>
      <td style="padding:12px 14px;border-bottom:1px solid #dce5ef;color:#334155">${escapeHtml(item.actorName || "QueueCraft user")}</td>
      <td style="padding:12px 14px;border-bottom:1px solid #dce5ef;color:#64748b;white-space:nowrap">${escapeHtml(item.createdAt.toLocaleString("en-GB"))}</td>
    </tr>`).join("");
  return `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#17324d">
    <div style="max-width:760px;margin:24px auto;background:#fff;border:1px solid #dce5ef;border-radius:8px;overflow:hidden">
      <div style="background:#ff7000;padding:22px 26px;color:#fff"><div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#fff0e5">QueueCraft</div><h1 style="margin:8px 0 0;font-size:22px">Topic changes digest</h1></div>
      <div style="padding:18px 26px"><p style="margin:0 0 16px;color:#475569">${items.length} change${items.length === 1 ? "" : "s"} affecting your notification groups.</p>
      <table role="presentation" style="width:100%;border-collapse:collapse;text-align:left;font-size:14px"><thead><tr style="background:#e8f1f8"><th style="padding:10px 14px">Topic</th><th style="padding:10px 14px">Change</th><th style="padding:10px 14px">Details</th><th style="padding:10px 14px">Changed by</th><th style="padding:10px 14px">Queued</th></tr></thead><tbody>${rows}</tbody></table></div>
      <div style="padding:14px 26px;background:#f8fafc;color:#64748b;font-size:12px">This email was generated by QueueCraft.</div>
    </div></body></html>`;
}

export function groupNotificationsByRecipient(items: Array<typeof notificationOutboxTable.$inferSelect>) {
  const groups = new Map<string, typeof items>();
  for (const item of items) {
    const key = item.recipient.trim().toLowerCase();
    const group = groups.get(key) ?? [];
    group.push(item);
    groups.set(key, group);
  }
  return groups;
}

export async function deliverPendingNotifications() {
  const { transporter, smtp } = await getTransporter();
  if (!transporter) {
    if (config.production) logger.error("SMTP is unavailable; notification delivery is blocked");
    return;
  }

  // A transaction-scoped advisory lock serializes polling across all server
  // instances, including the SMTP send itself, so rows cannot be sent twice
  // by overlapping timers.
  await db.transaction(async (tx) => {
    const lock = await tx.execute(sql`SELECT pg_try_advisory_xact_lock(731904221) AS locked`) as unknown as { rows: Array<{ locked: boolean }> };
    if (!lock.rows[0]?.locked) return;
    const now = new Date();

    const urgent = await tx.select().from(notificationOutboxTable).where(and(
      eq(notificationOutboxTable.action, BREAK_GLASS_NOTIFICATION_ACTION),
      inArray(notificationOutboxTable.status, ["pending", "failed"]),
      lte(notificationOutboxTable.nextAttemptAt, now),
    )).orderBy(notificationOutboxTable.createdAt).limit(25);
    for (const item of urgent) {
      try {
        // Security alerts bypass the digest delay and retain the original
        // subject and plain-text content alongside the branded HTML version.
        await transporter.sendMail({
          from: smtp.fromName ? { name: smtp.fromName, address: smtp.from } : smtp.from,
          to: item.recipient,
          subject: item.subject,
          text: item.body,
          html: renderUrgentNotificationHtml(item.subject, item.body),
        });
        await tx.update(notificationOutboxTable).set({
          status: "sent", sentAt: new Date(), error: null,
          attempts: sql`${notificationOutboxTable.attempts} + 1`,
        }).where(eq(notificationOutboxTable.id, item.id));
      } catch (error) {
        const attempts = item.attempts + 1;
        const delayMinutes = Math.min(60, 2 ** Math.min(attempts, 6));
        await tx.update(notificationOutboxTable).set({
          status: "failed", attempts,
          nextAttemptAt: new Date(Date.now() + delayMinutes * 60_000),
          error: error instanceof Error ? error.message.slice(0, 1000) : "SMTP delivery failed",
        }).where(eq(notificationOutboxTable.id, item.id));
        logger.error({ err: error, notificationId: item.id, attempts }, "Urgent security alert delivery failed");
      }
    }

    // Bound each pass by recipient count, not row count. Once a recipient is
    // due, all of their pending changes are loaded so one digest is never split.
    const recipientQuery = await tx.execute(sql`
      SELECT lower(recipient) AS recipient_key
      FROM notification_outbox
      WHERE status IN ('pending', 'failed')
        AND next_attempt_at <= ${now}
        AND action <> ${BREAK_GLASS_NOTIFICATION_ACTION}
      GROUP BY lower(recipient)
      ORDER BY min(created_at)
      LIMIT 25
    `) as unknown as { rows: Array<{ recipient_key: string }> };
    const recipientKeys = recipientQuery.rows.map((item) => item.recipient_key).sort();
    for (const recipient of recipientKeys) {
      await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(lower(${recipient})), 731904221)`);
    }
    const pending = recipientKeys.length ? await tx.select().from(notificationOutboxTable).where(
      and(
        inArray(notificationOutboxTable.status, ["pending", "failed"]),
        ne(notificationOutboxTable.action, BREAK_GLASS_NOTIFICATION_ACTION),
        inArray(sql`lower(${notificationOutboxTable.recipient})`, recipientKeys),
      ),
    ).orderBy(notificationOutboxTable.createdAt) : [];
    const recipientBatches = groupNotificationsByRecipient(pending);

    for (const items of recipientBatches.values()) {
      try {
        await transporter.sendMail({
          from: smtp.fromName ? { name: smtp.fromName, address: smtp.from } : smtp.from,
          to: items[0].recipient,
          subject: `QueueCraft topic changes (${items.length})`,
          text: items.map((item) => `${item.topicTitle || "Topic"} — ${item.action}\nChanged by: ${item.actorName || "QueueCraft user"}\n${item.body}`).join("\n\n"),
          html: renderNotificationDigest(items),
        });
        await tx.update(notificationOutboxTable).set({
          status: "sent",
          sentAt: new Date(),
          error: null,
          attempts: sql`${notificationOutboxTable.attempts} + 1`,
        }).where(inArray(notificationOutboxTable.id, items.map((item) => item.id)));
      } catch (error) {
        for (const item of items) {
          const attempts = item.attempts + 1;
          const delayMinutes = Math.min(60, 2 ** Math.min(attempts, 6));
          await tx.update(notificationOutboxTable).set({
            status: "failed",
            attempts,
            nextAttemptAt: new Date(Date.now() + delayMinutes * 60_000),
            error: error instanceof Error ? error.message.slice(0, 1000) : "SMTP delivery failed",
          }).where(eq(notificationOutboxTable.id, item.id));
        }
        logger.error({ err: error, recipient: items[0].recipient, notificationCount: items.length }, "SMTP digest delivery failed");
      }
    }
  });
}