apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-queuecraft-secrets-pvc
  namespace: queuecraft
  labels:
    team: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-queuecraft-certs-pvc
  namespace: queuecraft
  labels:
    team: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi